### ISSUE TITLE
Explain difference between and/or and &/|

### ISSUE THREAD

**Issue by ateucher** [bcgov/ds-intro-to-python#14]
But do it gently, and don't say 'bitwise' ;)

**Comment by lindsay-fredrick** [comment]
I'll add a small bit in my core-concepts section. I think just saying that `and` is for scalars and `&` is for vectors/element-wise will be good enough. But repeating it 2x in both our sections will reinforce that.

**Comment by lindsay-fredrick** [comment]
Content added to both sections, closing
