### ISSUE TITLE
Add good practice on naming things

### ISSUE THREAD

**Issue by ateucher** [bcgov/ds-intro-to-python#15]
we have [here](https://github.com/bcgov/ds-intro-to-python/blob/50061a2d3c56f43e367a7899b55febb36d739c89/course-content/02_core_data_structure_concepts.qmd#L34) a section with the hard _rules_ on naming things, but we should also add a bit on best practices - e.g., informative names, nouns for objects/variables, verbs for functions, etc.

**Comment by lindsay-fredrick** [comment]
I believe that @swayneh is going to be including that in one of his sections.
